#!/bin/bash
dataset="cityscapes"
train_gpu="0,1,2,3"
# train_gpu="4,5,6,7"
epoch=1
test_gpu="${train_gpu:0}"
ckpt="checkpoint/dino_vit_small_8.pth"
port=$(($RANDOM%100+1200))


# CNN
python train_front_door_cnn.py --dataset $dataset --ckpt $ckpt --gpu $train_gpu --port $port && python fine_tuning_cnn.py --dataset $dataset --epoch $epoch --ckpt $ckpt --gpu $train_gpu --port $port && python test_cnn.py --dataset $dataset --ckpt $ckpt --gpu $test_gpu

# DETR
# python train_front_door_detr.py --dataset $dataset --ckpt $ckpt --gpu $train_gpu --port $port && python fine_tuning_detr.py --epoch $epoch --dataset $dataset --ckpt $ckpt --gpu $train_gpu --port $port && python test_detr.py --dataset $dataset --ckpt $ckpt --gpu $test_gpu

# only test
# python test_cnn.py --dataset $dataset --ckpt $ckpt --gpu $test_gpu
# python test_detr.py --dataset $dataset --ckpt $ckpt --gpu $test_gpu