#!/bin/bash
######################################
# [OPTION] DATASET

# cocostuff27
# dataset="cocostuff27"
# reduced_dim=90

# cityscapes
# dataset="cityscapes"
# reduced_dim=90

# pascalvoc
# dataset="pascalvoc"
# reduced_dim=90

# coco-81
dataset="coco81"
reduced_dim=90

# coco-171
# dataset="coco171"
# reduced_dim=90
######################################

######################################
# [OPTION] STRUCTURE
structure="MLP"
# structure="TR"
######################################

######################################
# [OPTION] Self-Supervised Method

# DINO
ckpt="checkpoint/dino_vit_small_8.pth"
# ckpt="checkpoint/dino_vit_small_16.pth"
# ckpt="checkpoint/dino_vit_base_8.pth"
# ckpt="checkpoint/dino_vit_base_16.pth"

# DINOv2
# ckpt="checkpoint/dinov2_vit_base_14.pth"

# iBOT
# ckpt="checkpoint/ibot_vit_base_16.pth"

# MSN
# ckpt="checkpoint/msn_vit_small_16.pth"

# MAE
# ckpt="checkpoint/mae_vit_base_16.pth"
######################################

######################################
# GPU and PORT
if [ "$structure" = "MLP" ]
then
    train_gpu="0,1,2,3"
elif [ "$structure" = "TR" ]
then
    train_gpu="4,5,6,7"
fi

# Non-Changeable Variable
test_gpu="${train_gpu:0}"
port=$(($RANDOM%800+1200))
######################################

######################################
# [STEP1] MEDIATOR
python train_mediator.py --epoch 1 --dataset $dataset --ckpt $ckpt --gpu $train_gpu --port $port
######################################

######################################
# [STEP2] CAUSE
if [ "$structure" = "MLP" ]
then 
    python fine_tuning_mlp.py --dataset $dataset --epoch 1 --ckpt $ckpt --gpu $train_gpu --port $port --reduced_dim $reduced_dim
elif [ "$structure" = "TR" ]
then 
    python fine_tuning_tr.py --epoch 5 --dataset $dataset --ckpt $ckpt --gpu $train_gpu --port $port --reduced_dim $reduced_dim
fi
######################################

######################################
# TEST
if [ "$structure" = "MLP" ]
then 
    python test_mlp.py --dataset $dataset --ckpt $ckpt --gpu $test_gpu --reduced_dim $reduced_dim
elif [ "$structure" = "TR" ]
then 
    python test_tr.py --dataset $dataset --ckpt $ckpt --gpu $test_gpu --reduced_dim $reduced_dim
fi
######################################

######################################
# [OPTION] CAUSE-MLP
# python train_front_door_mlp.py --dataset $dataset --ckpt $ckpt --gpu $train_gpu --port $port --reduced_dim $reduced_dim && python fine_tuning_mlp.py --dataset $dataset --epoch 1 --ckpt $ckpt --gpu $train_gpu --port $port && python test_mlp.py --dataset $dataset --ckpt $ckpt --gpu $test_gpu --reduced_dim $reduced_dim
# python train_front_door_tr.py --dataset $dataset --ckpt $ckpt --gpu $train_gpu --port $port && python fine_tuning_tr.py --epoch 5 --dataset $dataset --ckpt $ckpt --gpu $train_gpu --port $port && python test_tr.py --dataset $dataset --ckpt $ckpt --gpu $test_gpu
######################################

######################################
# [OPTION] LINEAR PROBING
# python linear_probing_mlp.py --epoch 5 --dataset $dataset --ckpt $ckpt --gpu $train_gpu --port $port --reduced_dim $reduced_dim
# python linear_probing_tr.py --epoch 5 --dataset $dataset --ckpt $ckpt --gpu $train_gpu --port $port --reduced_dim $reduced_dim
######################################